// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBux_VUosShq5ZTnApJQpoGjnCXOqbOUgI',
    appId: '1:252296205232:web:fa51684908317af8ecbc75',
    messagingSenderId: '252296205232',
    projectId: 'arewa-health',
    authDomain: 'arewa-health.firebaseapp.com',
    storageBucket: 'arewa-health.firebasestorage.app',
    measurementId: 'G-L6HZC24P72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrwjOv2lWNUZMusqRFKyD8sP8vL3hDCl8',
    appId: '1:252296205232:android:41078be00b6a7dddecbc75',
    messagingSenderId: '252296205232',
    projectId: 'arewa-health',
    storageBucket: 'arewa-health.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw5JNvRkHBYwqp4WWbnAsHjSgA1wNQMh8',
    appId: '1:252296205232:ios:4033d6e72ec86d30ecbc75',
    messagingSenderId: '252296205232',
    projectId: 'arewa-health',
    storageBucket: 'arewa-health.firebasestorage.app',
    iosBundleId: 'com.example.arewaHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw5JNvRkHBYwqp4WWbnAsHjSgA1wNQMh8',
    appId: '1:252296205232:ios:4033d6e72ec86d30ecbc75',
    messagingSenderId: '252296205232',
    projectId: 'arewa-health',
    storageBucket: 'arewa-health.firebasestorage.app',
    iosBundleId: 'com.example.arewaHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBux_VUosShq5ZTnApJQpoGjnCXOqbOUgI',
    appId: '1:252296205232:web:2cd0072d694a9ff4ecbc75',
    messagingSenderId: '252296205232',
    projectId: 'arewa-health',
    authDomain: 'arewa-health.firebaseapp.com',
    storageBucket: 'arewa-health.firebasestorage.app',
    measurementId: 'G-T0JKJG8CQ4',
  );
}
